"""MySQL 5.7 standalone baseline; PostgreSQL revisions remain immutable.

This is a frozen explicit DDL snapshot, not metadata.create_all.
"""

from sqlalchemy import inspect
from alembic import op

revision = "mysql57_0001"
down_revision = None
branch_labels = None
depends_on = None

DDL = [
    "CREATE TABLE rd_comment (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tentity_type VARCHAR(32) NOT NULL, \n\tentity_id BIGINT NOT NULL, \n\tcontent TEXT NOT NULL, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_rd_comment_entity_id ON rd_comment (entity_id)",
    "CREATE INDEX ix_rd_comment_entity_type ON rd_comment (entity_type)",
    "CREATE TABLE sys_business_system (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tcode VARBINARY(256) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tenabled BOOL NOT NULL, \n\tsort_order INTEGER NOT NULL, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (code)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE TRIGGER `domain_sys_business_system_insert` BEFORE INSERT ON `sys_business_system` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_business_system.code'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_business_system.enabled'; END IF; END",
    "CREATE TRIGGER `domain_sys_business_system_update` BEFORE UPDATE ON `sys_business_system` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_business_system.code'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_business_system.enabled'; END IF; END",
    "CREATE TABLE sys_dictionary (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tcode VARBINARY(256) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tdescription VARCHAR(500), \n\tenabled BOOL NOT NULL, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE UNIQUE INDEX ix_sys_dictionary_code ON sys_dictionary (code)",
    "CREATE TRIGGER `domain_sys_dictionary_insert` BEFORE INSERT ON `sys_dictionary` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_dictionary.code'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_dictionary.enabled'; END IF; END",
    "CREATE TRIGGER `domain_sys_dictionary_update` BEFORE UPDATE ON `sys_dictionary` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_dictionary.code'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_dictionary.enabled'; END IF; END",
    "CREATE TABLE sys_file (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tstorage_key VARBINARY(2000) NOT NULL, \n\toriginal_name VARCHAR(255) NOT NULL, \n\tmime_type VARCHAR(128) NOT NULL, \n\tsize BIGINT NOT NULL, \n\tsha256 VARCHAR(64) NOT NULL, \n\tstorage_driver VARCHAR(5) NOT NULL, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (storage_key), \n\tCONSTRAINT storage_driver CHECK (storage_driver IN ('LOCAL', 'S3'))\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_sys_file_sha256 ON sys_file (sha256)",
    "CREATE TRIGGER `domain_sys_file_insert` BEFORE INSERT ON `sys_file` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`storage_key` USING utf8mb4)) > 500 OR NOT (CONVERT(CONVERT(NEW.`storage_key` USING utf8mb4) USING binary) <=> NEW.`storage_key`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_file.storage_key'; END IF; IF BINARY NEW.`storage_driver` NOT IN ('LOCAL','S3') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_file.storage_driver'; END IF; END",
    "CREATE TRIGGER `domain_sys_file_update` BEFORE UPDATE ON `sys_file` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`storage_key` USING utf8mb4)) > 500 OR NOT (CONVERT(CONVERT(NEW.`storage_key` USING utf8mb4) USING binary) <=> NEW.`storage_key`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_file.storage_key'; END IF; IF BINARY NEW.`storage_driver` NOT IN ('LOCAL','S3') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_file.storage_driver'; END IF; END",
    "CREATE TABLE sys_permission (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tcode VARBINARY(512) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tcategory VARCHAR(32) NOT NULL, \n\tPRIMARY KEY (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE UNIQUE INDEX ix_sys_permission_code ON sys_permission (code)",
    "CREATE TABLE sys_role (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tcode VARBINARY(256) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tdata_scope VARCHAR(4) NOT NULL, \n\tenabled BOOL NOT NULL, \n\tis_system BOOL NOT NULL DEFAULT false, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (code), \n\tCONSTRAINT data_scope CHECK (data_scope IN ('SELF', 'TEAM', 'ALL'))\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE TRIGGER `domain_sys_role_insert` BEFORE INSERT ON `sys_role` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_role.code'; END IF; IF BINARY NEW.`data_scope` NOT IN ('SELF','TEAM','ALL') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_role.data_scope'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_role.enabled'; END IF; IF NEW.`is_system` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_role.is_system'; END IF; END",
    "CREATE TRIGGER `domain_sys_role_update` BEFORE UPDATE ON `sys_role` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_role.code'; END IF; IF BINARY NEW.`data_scope` NOT IN ('SELF','TEAM','ALL') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_role.data_scope'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_role.enabled'; END IF; IF NEW.`is_system` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_role.is_system'; END IF; END",
    "CREATE TABLE sys_user (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tusername VARBINARY(256) NOT NULL, \n\tdisplay_name VARCHAR(100) NOT NULL, \n\tpassword_hash VARCHAR(255) NOT NULL, \n\temail VARCHAR(255), \n\tmobile VARCHAR(32), \n\tstatus VARCHAR(8) NOT NULL, \n\tmust_change_password BOOL NOT NULL, \n\tlast_login_at DATETIME(6), \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT user_status CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED'))\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_sys_user_status ON sys_user (status)",
    "CREATE UNIQUE INDEX ix_sys_user_username ON sys_user (username)",
    "CREATE TRIGGER `domain_sys_user_insert` BEFORE INSERT ON `sys_user` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`username` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`username` USING utf8mb4) USING binary) <=> NEW.`username`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_user.username'; END IF; IF BINARY NEW.`status` NOT IN ('ACTIVE','DISABLED','LOCKED') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_user.status'; END IF; IF NEW.`must_change_password` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_user.must_change_password'; END IF; END",
    "CREATE TRIGGER `domain_sys_user_update` BEFORE UPDATE ON `sys_user` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`username` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`username` USING utf8mb4) USING binary) <=> NEW.`username`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_user.username'; END IF; IF BINARY NEW.`status` NOT IN ('ACTIVE','DISABLED','LOCKED') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_user.status'; END IF; IF NEW.`must_change_password` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_user.must_change_password'; END IF; END",
    "CREATE TABLE rd_version (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tversion_no VARBINARY(128) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tstatus VARCHAR(10) NOT NULL, \n\towner_id BIGINT, \n\tplanned_release_date DATE, \n\treleased_at DATETIME(6), \n\tdescription TEXT, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT version_status CHECK (status IN ('PLANNING', 'DEVELOPING', 'TESTING', 'READY', 'RELEASED', 'CANCELED')), \n\tFOREIGN KEY(owner_id) REFERENCES sys_user (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_rd_version_status ON rd_version (status)",
    "CREATE UNIQUE INDEX ix_rd_version_version_no ON rd_version (version_no)",
    "CREATE TRIGGER `domain_rd_version_insert` BEFORE INSERT ON `rd_version` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`version_no` USING utf8mb4)) > 32 OR NOT (CONVERT(CONVERT(NEW.`version_no` USING utf8mb4) USING binary) <=> NEW.`version_no`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_version.version_no'; END IF; IF BINARY NEW.`status` NOT IN ('PLANNING','DEVELOPING','TESTING','READY','RELEASED','CANCELED') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_version.status'; END IF; END",
    "CREATE TRIGGER `domain_rd_version_update` BEFORE UPDATE ON `rd_version` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`version_no` USING utf8mb4)) > 32 OR NOT (CONVERT(CONVERT(NEW.`version_no` USING utf8mb4) USING binary) <=> NEW.`version_no`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_version.version_no'; END IF; IF BINARY NEW.`status` NOT IN ('PLANNING','DEVELOPING','TESTING','READY','RELEASED','CANCELED') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_version.status'; END IF; END",
    "CREATE TABLE sys_attachment_relation (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tfile_id BIGINT NOT NULL, \n\tentity_type VARCHAR(32) NOT NULL, \n\tentity_id BIGINT NOT NULL, \n\tcreated_at DATETIME(6) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_attachment_entity_file UNIQUE (entity_type, entity_id, file_id), \n\tFOREIGN KEY(file_id) REFERENCES sys_file (id) ON DELETE CASCADE\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_attachment_entity_type_entity_id ON sys_attachment_relation (entity_type, entity_id)",
    "CREATE INDEX ix_attachment_file_id ON sys_attachment_relation (file_id)",
    "CREATE TABLE sys_business_module (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tsystem_id BIGINT NOT NULL, \n\tcode VARBINARY(256) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tenabled BOOL NOT NULL, \n\tsort_order INTEGER NOT NULL, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_module_system_code UNIQUE (system_id, code), \n\tFOREIGN KEY(system_id) REFERENCES sys_business_system (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_sys_business_module_system_id ON sys_business_module (system_id)",
    "CREATE TRIGGER `domain_sys_business_module_insert` BEFORE INSERT ON `sys_business_module` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_business_module.code'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_business_module.enabled'; END IF; END",
    "CREATE TRIGGER `domain_sys_business_module_update` BEFORE UPDATE ON `sys_business_module` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_business_module.code'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_business_module.enabled'; END IF; END",
    "CREATE TABLE sys_dictionary_item (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tdictionary_id BIGINT NOT NULL, \n\tcode VARBINARY(256) NOT NULL, \n\tlabel VARCHAR(100) NOT NULL, \n\tvalue VARCHAR(255) NOT NULL, \n\tsort_order INTEGER NOT NULL, \n\tenabled BOOL NOT NULL, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_dictionary_item_dictionary_code UNIQUE (dictionary_id, code), \n\tFOREIGN KEY(dictionary_id) REFERENCES sys_dictionary (id) ON DELETE CASCADE\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_sys_dictionary_item_dictionary_id ON sys_dictionary_item (dictionary_id)",
    "CREATE TRIGGER `domain_sys_dictionary_item_insert` BEFORE INSERT ON `sys_dictionary_item` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_dictionary_item.code'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_dictionary_item.enabled'; END IF; END",
    "CREATE TRIGGER `domain_sys_dictionary_item_update` BEFORE UPDATE ON `sys_dictionary_item` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 64 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_dictionary_item.code'; END IF; IF NEW.`enabled` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_dictionary_item.enabled'; END IF; END",
    "CREATE TABLE sys_notification (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tuser_id BIGINT NOT NULL, \n\ttype VARCHAR(11) NOT NULL, \n\ttitle VARCHAR(200) NOT NULL, \n\tcontent TEXT NOT NULL, \n\tentity_type VARCHAR(32), \n\tentity_id BIGINT, \n\tread_at DATETIME(6), \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES sys_user (id), \n\tCONSTRAINT notification_type CHECK (type IN ('SYSTEM', 'FEEDBACK', 'REQUIREMENT', 'VERSION', 'RELEASE'))\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_sys_notification_read_at ON sys_notification (read_at)",
    "CREATE INDEX ix_sys_notification_type ON sys_notification (type)",
    "CREATE INDEX ix_sys_notification_user_id ON sys_notification (user_id)",
    "CREATE TRIGGER `domain_sys_notification_insert` BEFORE INSERT ON `sys_notification` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF BINARY NEW.`type` NOT IN ('SYSTEM','FEEDBACK','REQUIREMENT','VERSION','RELEASE') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_notification.type'; END IF; END",
    "CREATE TRIGGER `domain_sys_notification_update` BEFORE UPDATE ON `sys_notification` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF BINARY NEW.`type` NOT IN ('SYSTEM','FEEDBACK','REQUIREMENT','VERSION','RELEASE') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_notification.type'; END IF; END",
    "CREATE TABLE sys_operation_log (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tentity_type VARCHAR(32) NOT NULL, \n\tentity_id BIGINT, \n\taction VARCHAR(64) NOT NULL, \n\toperator_id BIGINT, \n\trequest_id VARCHAR(64), \n\tip_address VARCHAR(64), \n\tuser_agent VARCHAR(512), \n\tbefore_data JSON, \n\tafter_data JSON, \n\tcreated_at DATETIME(6) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(operator_id) REFERENCES sys_user (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_sys_operation_log_action ON sys_operation_log (action)",
    "CREATE INDEX ix_sys_operation_log_created_at ON sys_operation_log (created_at)",
    "CREATE INDEX ix_sys_operation_log_entity_id ON sys_operation_log (entity_id)",
    "CREATE INDEX ix_sys_operation_log_entity_type ON sys_operation_log (entity_type)",
    "CREATE INDEX ix_sys_operation_log_operator_id ON sys_operation_log (operator_id)",
    "CREATE INDEX ix_sys_operation_log_request_id ON sys_operation_log (request_id)",
    "CREATE TABLE sys_refresh_session (\n\tid VARCHAR(32) NOT NULL, \n\tuser_id BIGINT NOT NULL, \n\ttoken_jti VARCHAR(32) NOT NULL, \n\texpires_at DATETIME(6) NOT NULL, \n\trevoked_at DATETIME(6), \n\trevoked_reason VARCHAR(64), \n\tlast_used_at DATETIME(6), \n\tcreated_at DATETIME(6) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES sys_user (id) ON DELETE CASCADE, \n\tUNIQUE (token_jti)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_sys_refresh_session_expires_at ON sys_refresh_session (expires_at)",
    "CREATE INDEX ix_sys_refresh_session_user_id ON sys_refresh_session (user_id)",
    "CREATE TABLE sys_role_permission (\n\trole_id BIGINT NOT NULL, \n\tpermission_id BIGINT NOT NULL, \n\tPRIMARY KEY (role_id, permission_id), \n\tFOREIGN KEY(role_id) REFERENCES sys_role (id), \n\tFOREIGN KEY(permission_id) REFERENCES sys_permission (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE TABLE sys_user_role (\n\tuser_id BIGINT NOT NULL, \n\trole_id BIGINT NOT NULL, \n\tPRIMARY KEY (user_id, role_id), \n\tFOREIGN KEY(user_id) REFERENCES sys_user (id), \n\tFOREIGN KEY(role_id) REFERENCES sys_role (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE TABLE rd_feedback (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tfeedback_no VARBINARY(128) NOT NULL, \n\ttitle VARCHAR(200) NOT NULL, \n\tfeedback_type VARCHAR(20) NOT NULL, \n\turgency VARCHAR(8) NOT NULL, \n\tstatus VARCHAR(18) NOT NULL, \n\tsystem_id BIGINT, \n\tmodule_id BIGINT, \n\tsubmitter_id BIGINT NOT NULL, \n\tdescription TEXT NOT NULL, \n\texpected_result TEXT, \n\tactual_result TEXT, \n\treproduce_steps TEXT, \n\tduplicate_of_id BIGINT, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT feedback_type CHECK (feedback_type IN ('NEW_FEATURE', 'FEATURE_OPTIMIZATION', 'SYSTEM_ISSUE', 'DATA_ISSUE', 'UI_UX', 'OTHER')), \n\tCONSTRAINT feedback_urgency CHECK (urgency IN ('NORMAL', 'URGENT', 'CRITICAL')), \n\tCONSTRAINT feedback_status CHECK (status IN ('NEW', 'ACCEPTED', 'REQUIREMENT_LINKED', 'ONLINE', 'DUPLICATE', 'CANNOT_REPRODUCE', 'CLOSED')), \n\tFOREIGN KEY(system_id) REFERENCES sys_business_system (id), \n\tFOREIGN KEY(module_id) REFERENCES sys_business_module (id), \n\tFOREIGN KEY(submitter_id) REFERENCES sys_user (id), \n\tFOREIGN KEY(duplicate_of_id) REFERENCES rd_feedback (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_feedback_system_module ON rd_feedback (system_id, module_id)",
    "CREATE UNIQUE INDEX ix_rd_feedback_feedback_no ON rd_feedback (feedback_no)",
    "CREATE INDEX ix_rd_feedback_status ON rd_feedback (status)",
    "CREATE INDEX ix_rd_feedback_submitter_id ON rd_feedback (submitter_id)",
    "CREATE TRIGGER `domain_rd_feedback_insert` BEFORE INSERT ON `rd_feedback` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`feedback_no` USING utf8mb4)) > 32 OR NOT (CONVERT(CONVERT(NEW.`feedback_no` USING utf8mb4) USING binary) <=> NEW.`feedback_no`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_feedback.feedback_no'; END IF; IF BINARY NEW.`feedback_type` NOT IN ('NEW_FEATURE','FEATURE_OPTIMIZATION','SYSTEM_ISSUE','DATA_ISSUE','UI_UX','OTHER') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_feedback.feedback_type'; END IF; IF BINARY NEW.`urgency` NOT IN ('NORMAL','URGENT','CRITICAL') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_feedback.urgency'; END IF; IF BINARY NEW.`status` NOT IN ('NEW','ACCEPTED','REQUIREMENT_LINKED','ONLINE','DUPLICATE','CANNOT_REPRODUCE','CLOSED') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_feedback.status'; END IF; END",
    "CREATE TRIGGER `domain_rd_feedback_update` BEFORE UPDATE ON `rd_feedback` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`feedback_no` USING utf8mb4)) > 32 OR NOT (CONVERT(CONVERT(NEW.`feedback_no` USING utf8mb4) USING binary) <=> NEW.`feedback_no`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_feedback.feedback_no'; END IF; IF BINARY NEW.`feedback_type` NOT IN ('NEW_FEATURE','FEATURE_OPTIMIZATION','SYSTEM_ISSUE','DATA_ISSUE','UI_UX','OTHER') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_feedback.feedback_type'; END IF; IF BINARY NEW.`urgency` NOT IN ('NORMAL','URGENT','CRITICAL') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_feedback.urgency'; END IF; IF BINARY NEW.`status` NOT IN ('NEW','ACCEPTED','REQUIREMENT_LINKED','ONLINE','DUPLICATE','CANNOT_REPRODUCE','CLOSED') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_feedback.status'; END IF; END",
    "CREATE TABLE rd_release (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tversion_id BIGINT NOT NULL, \n\treleased_at DATETIME(6) NOT NULL, \n\tresult VARCHAR(7) NOT NULL, \n\trelease_notes TEXT NOT NULL, \n\trollback_notes TEXT, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_release_version_id UNIQUE (version_id), \n\tFOREIGN KEY(version_id) REFERENCES rd_version (id), \n\tCONSTRAINT release_result CHECK (result IN ('SUCCESS'))\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE TRIGGER `domain_rd_release_insert` BEFORE INSERT ON `rd_release` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF BINARY NEW.`result` NOT IN ('SUCCESS') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_release.result'; END IF; END",
    "CREATE TRIGGER `domain_rd_release_update` BEFORE UPDATE ON `rd_release` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF BINARY NEW.`result` NOT IN ('SUCCESS') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_release.result'; END IF; END",
    "CREATE TABLE rd_requirement (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\trequirement_no VARBINARY(128) NOT NULL, \n\ttitle VARCHAR(200) NOT NULL, \n\trequirement_type VARCHAR(32) NOT NULL, \n\tsource VARCHAR(8) NOT NULL, \n\tpriority VARCHAR(2) NOT NULL, \n\tstatus VARCHAR(10) NOT NULL, \n\tsystem_id BIGINT, \n\tmodule_id BIGINT, \n\towner_id BIGINT, \n\tdescription TEXT NOT NULL, \n\tacceptance_criteria TEXT, \n\tcreated_at DATETIME(6) NOT NULL, \n\tcreated_by BIGINT, \n\tupdated_at DATETIME(6) NOT NULL, \n\tupdated_by BIGINT, \n\trevision INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT requirement_source CHECK (source IN ('DIRECT', 'FEEDBACK')), \n\tCONSTRAINT priority CHECK (priority IN ('P0', 'P1', 'P2', 'P3', 'P4')), \n\tCONSTRAINT requirement_status CHECK (status IN ('DRAFT', 'CONFIRMED', 'PLANNED', 'DEVELOPING', 'TESTING', 'DONE', 'ONLINE', 'PAUSED', 'CANCELED')), \n\tFOREIGN KEY(system_id) REFERENCES sys_business_system (id), \n\tFOREIGN KEY(module_id) REFERENCES sys_business_module (id), \n\tFOREIGN KEY(owner_id) REFERENCES sys_user (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_rd_requirement_owner_id ON rd_requirement (owner_id)",
    "CREATE INDEX ix_rd_requirement_priority ON rd_requirement (priority)",
    "CREATE UNIQUE INDEX ix_rd_requirement_requirement_no ON rd_requirement (requirement_no)",
    "CREATE INDEX ix_rd_requirement_status ON rd_requirement (status)",
    "CREATE INDEX ix_requirement_system_module ON rd_requirement (system_id, module_id)",
    "CREATE TRIGGER `domain_rd_requirement_insert` BEFORE INSERT ON `rd_requirement` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`requirement_no` USING utf8mb4)) > 32 OR NOT (CONVERT(CONVERT(NEW.`requirement_no` USING utf8mb4) USING binary) <=> NEW.`requirement_no`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement.requirement_no'; END IF; IF BINARY NEW.`source` NOT IN ('DIRECT','FEEDBACK') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement.source'; END IF; IF BINARY NEW.`priority` NOT IN ('P0','P1','P2','P3','P4') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement.priority'; END IF; IF BINARY NEW.`status` NOT IN ('DRAFT','CONFIRMED','PLANNED','DEVELOPING','TESTING','DONE','ONLINE','PAUSED','CANCELED') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement.status'; END IF; END",
    "CREATE TRIGGER `domain_rd_requirement_update` BEFORE UPDATE ON `rd_requirement` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`requirement_no` USING utf8mb4)) > 32 OR NOT (CONVERT(CONVERT(NEW.`requirement_no` USING utf8mb4) USING binary) <=> NEW.`requirement_no`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement.requirement_no'; END IF; IF BINARY NEW.`source` NOT IN ('DIRECT','FEEDBACK') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement.source'; END IF; IF BINARY NEW.`priority` NOT IN ('P0','P1','P2','P3','P4') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement.priority'; END IF; IF BINARY NEW.`status` NOT IN ('DRAFT','CONFIRMED','PLANNED','DEVELOPING','TESTING','DONE','ONLINE','PAUSED','CANCELED') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement.status'; END IF; END",
    "CREATE TABLE rd_requirement_feedback (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\trequirement_id BIGINT NOT NULL, \n\tfeedback_id BIGINT NOT NULL, \n\tis_primary BOOL NOT NULL, \n\tcreated_at DATETIME(6) NOT NULL, \n\tprimary_feedback_id BIGINT GENERATED ALWAYS AS (IF(is_primary = 1, feedback_id, NULL)) STORED, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_requirement_feedback_pair UNIQUE (requirement_id, feedback_id), \n\tFOREIGN KEY(requirement_id) REFERENCES rd_requirement (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(feedback_id) REFERENCES rd_feedback (id) ON DELETE RESTRICT\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_rd_requirement_feedback_feedback_id ON rd_requirement_feedback (feedback_id)",
    "CREATE INDEX ix_rd_requirement_feedback_requirement_id ON rd_requirement_feedback (requirement_id)",
    "CREATE UNIQUE INDEX uq_feedback_primary_relation ON rd_requirement_feedback (primary_feedback_id)",
    "CREATE TRIGGER `domain_rd_requirement_feedback_insert` BEFORE INSERT ON `rd_requirement_feedback` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF NEW.`is_primary` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement_feedback.is_primary'; END IF; END",
    "CREATE TRIGGER `domain_rd_requirement_feedback_update` BEFORE UPDATE ON `rd_requirement_feedback` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF NEW.`is_primary` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_requirement_feedback.is_primary'; END IF; END",
    "CREATE TABLE rd_version_requirement (\n\tid BIGINT NOT NULL AUTO_INCREMENT, \n\tversion_id BIGINT NOT NULL, \n\trequirement_id BIGINT NOT NULL, \n\tactive BOOL NOT NULL, \n\tadded_at DATETIME(6) NOT NULL, \n\tadded_by BIGINT, \n\tremoved_at DATETIME(6), \n\tremoved_by BIGINT, \n\tremoved_reason VARCHAR(500), \n\tactive_requirement_id BIGINT GENERATED ALWAYS AS (IF(active = 1, requirement_id, NULL)) STORED, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(version_id) REFERENCES rd_version (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(requirement_id) REFERENCES rd_requirement (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(added_by) REFERENCES sys_user (id), \n\tFOREIGN KEY(removed_by) REFERENCES sys_user (id)\n)ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE utf8mb4_bin",
    "CREATE INDEX ix_rd_version_requirement_active ON rd_version_requirement (active)",
    "CREATE INDEX ix_rd_version_requirement_requirement_id ON rd_version_requirement (requirement_id)",
    "CREATE INDEX ix_rd_version_requirement_version_id ON rd_version_requirement (version_id)",
    "CREATE UNIQUE INDEX uq_requirement_active_version ON rd_version_requirement (active_requirement_id)",
    "CREATE TRIGGER `domain_rd_version_requirement_insert` BEFORE INSERT ON `rd_version_requirement` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF NEW.`active` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_version_requirement.active'; END IF; END",
    "CREATE TRIGGER `domain_rd_version_requirement_update` BEFORE UPDATE ON `rd_version_requirement` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF NEW.`active` NOT IN (0,1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid rd_version_requirement.active'; END IF; END",
    "CREATE TRIGGER `domain_sys_permission_insert` BEFORE INSERT ON `sys_permission` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 128 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_permission.code'; END IF; END",
    "CREATE TRIGGER `domain_sys_permission_update` BEFORE UPDATE ON `sys_permission` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; IF CHAR_LENGTH(CONVERT(NEW.`code` USING utf8mb4)) > 128 OR NOT (CONVERT(CONVERT(NEW.`code` USING utf8mb4) USING binary) <=> NEW.`code`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid sys_permission.code'; END IF; END",
    "CREATE TRIGGER `domain_rd_comment_insert` BEFORE INSERT ON `rd_comment` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_rd_comment_update` BEFORE UPDATE ON `rd_comment` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_rd_comment_delete` BEFORE DELETE ON `rd_comment` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_business_system_delete` BEFORE DELETE ON `sys_business_system` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_dictionary_delete` BEFORE DELETE ON `sys_dictionary` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_file_delete` BEFORE DELETE ON `sys_file` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_permission_delete` BEFORE DELETE ON `sys_permission` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_role_delete` BEFORE DELETE ON `sys_role` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_user_delete` BEFORE DELETE ON `sys_user` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_rd_version_delete` BEFORE DELETE ON `rd_version` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_attachment_relation_insert` BEFORE INSERT ON `sys_attachment_relation` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_attachment_relation_update` BEFORE UPDATE ON `sys_attachment_relation` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_attachment_relation_delete` BEFORE DELETE ON `sys_attachment_relation` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_business_module_delete` BEFORE DELETE ON `sys_business_module` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_dictionary_item_delete` BEFORE DELETE ON `sys_dictionary_item` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_notification_delete` BEFORE DELETE ON `sys_notification` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_operation_log_insert` BEFORE INSERT ON `sys_operation_log` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_operation_log_update` BEFORE UPDATE ON `sys_operation_log` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_operation_log_delete` BEFORE DELETE ON `sys_operation_log` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_refresh_session_insert` BEFORE INSERT ON `sys_refresh_session` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_refresh_session_update` BEFORE UPDATE ON `sys_refresh_session` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_refresh_session_delete` BEFORE DELETE ON `sys_refresh_session` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_role_permission_insert` BEFORE INSERT ON `sys_role_permission` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_role_permission_update` BEFORE UPDATE ON `sys_role_permission` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_role_permission_delete` BEFORE DELETE ON `sys_role_permission` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_user_role_insert` BEFORE INSERT ON `sys_user_role` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_user_role_update` BEFORE UPDATE ON `sys_user_role` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_sys_user_role_delete` BEFORE DELETE ON `sys_user_role` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_rd_feedback_delete` BEFORE DELETE ON `rd_feedback` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_rd_release_delete` BEFORE DELETE ON `rd_release` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_rd_requirement_delete` BEFORE DELETE ON `rd_requirement` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_rd_requirement_feedback_delete` BEFORE DELETE ON `rd_requirement_feedback` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
    "CREATE TRIGGER `domain_rd_version_requirement_delete` BEFORE DELETE ON `rd_version_requirement` FOR EACH ROW BEGIN IF @@foreign_key_checks <> 1 OR @@unique_checks <> 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IterFlow requires foreign_key_checks and unique_checks'; END IF; END",
]


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name != "mysql":
        raise RuntimeError("MySQL migration requires MySQL")
    existing = set(inspect(bind).get_table_names()) - {"alembic_version"}
    if existing:
        raise RuntimeError(
            "MySQL baseline requires an empty database; partial DDL must be inspected explicitly"
        )
    for statement in DDL:
        op.execute(statement)


def downgrade():
    raise RuntimeError(
        "Destructive MySQL baseline downgrade is disabled; use an isolated empty test database"
    )
